[[redirects]]
from = "/feedback-form"
to = "/feedback-form.html"
status = 200

[[redirects]]
from = "/thank-you"
to = "/thank-you.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
